version: "3.9"
services:
  vitaledge-crypt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084" # Map container port 8084 to host port 8084
    restart: unless-stopped
